/*
 * JS for profileScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '682d253c-04fc-41c1-8754-3d0454b87d54';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "profileScreen",
    "location": "profileScreen.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "chatScreen",
    "location": "chatScreen.html"
}];

profileScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_34': 'profileScreen_mobileimage_34',
        'mobilegrid_8': 'profileScreen_mobilegrid_8',
        'mobilegridcell_9': 'profileScreen_mobilegridcell_9',
        'mobiletextinput_5': 'profileScreen_mobiletextinput_5',
        'mobilegridcell_11': 'profileScreen_mobilegridcell_11',
        'mobiletextinput_6': 'profileScreen_mobiletextinput_6',
        'mobiletextarea_7': 'profileScreen_mobiletextarea_7',
        'mobiletextinput_36': 'profileScreen_mobiletextinput_36',
        'mobileimage_20': 'profileScreen_mobileimage_20',
        'mobilegrid_13': 'profileScreen_mobilegrid_13',
        'mobilegridcell_14': 'profileScreen_mobilegridcell_14',
        'mobiletextinput_22': 'profileScreen_mobiletextinput_22',
        'mobilegridcell_16': 'profileScreen_mobilegridcell_16',
        'mobiletextinput_23': 'profileScreen_mobiletextinput_23',
        'mobilegridcell_24': 'profileScreen_mobilegridcell_24',
        'mobilebutton_28': 'profileScreen_mobilebutton_28',
        'mobilebutton_27': 'profileScreen_mobilebutton_27',
        'mobilelabel_33': 'profileScreen_mobilelabel_33',
        'mobilebutton_37': 'profileScreen_mobilebutton_37',
        'mobilenavbar_2': 'profileScreen_mobilenavbar_2',
        'mobilenavbaritem_3': 'profileScreen_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'profileScreen_mobilenavbaritem_4',
        'mobilenavbaritem_38': 'profileScreen_mobilenavbaritem_38'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'profileScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    MerchantSave1 = new Apperyio.DataSource(MerchantSave, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("profileScreen");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['EstbName'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_5',
            'ATTR': 'value'
        }, {
            'PATH': ['Address'],
            'TYPE': 'STRING',
            'ID': 'mobiletextarea_7',
            'ATTR': 'value'
        }, {
            'PATH': ['Phone'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_36',
            'ATTR': 'value'
        }, {
            'PATH': ['EstbOwner'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_6',
            'ATTR': 'value'
        }, {
            'PATH': ['SinchUsername'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_22',
            'ATTR': 'value'
        }, {
            'PATH': ['SinchPassword'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_23',
            'ATTR': 'value'
        }, {
            'PATH': ['Merchantid'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'demouuid'
        }]
    });

    datasources.push(MerchantSave1);

    /*
     * Events and handlers
     */

    // Before Show
    var profileScreen_beforeshow = function() {
            Apperyio.CurrentScreen = "profileScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var profileScreen_onLoad = function() {
            profileScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            profileScreen_deviceEvents();
            profileScreen_windowEvents();
            profileScreen_elementsEvents();
        };

    // screen window events
    var profileScreen_windowEvents = function() {

            $('#profileScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var profileScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var profileScreen_elementsExtraJS = function() {
            // screen (profileScreen) extra code

        };

    // screen elements handler
    var profileScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#profileScreen_mobilecontainer1 [name="mobilebutton_37"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            MerchantSave1.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#profileScreen_mobilecontainer1 [name="mobilebutton_37"]');

            $(document).off("click", '#profileScreen_mobilefooter1 [name="mobilenavbaritem_3"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('startScreen', {
                            transition: 'slide',
                            reverse: true
                        });

                    }
                },
            }, '#profileScreen_mobilefooter1 [name="mobilenavbaritem_3"]');

            $(document).off("click", '#profileScreen_mobilefooter1 [name="mobilenavbaritem_38"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('chatScreen', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#profileScreen_mobilefooter1 [name="mobilenavbaritem_38"]');

        };

    $(document).off("pagebeforeshow", "#profileScreen").on("pagebeforeshow", "#profileScreen", function(event, ui) {
        profileScreen_beforeshow();
    });

    if (runBeforeShow) {
        profileScreen_beforeshow();
    } else {
        profileScreen_onLoad();
    }
};

$(document).off("pagecreate", "#profileScreen").on("pagecreate", "#profileScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    profileScreen_js();
});