/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '682d253c-04fc-41c1-8754-3d0454b87d54';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "profileScreen",
    "location": "profileScreen.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "chatScreen",
    "location": "chatScreen.html"
}];

startScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_28': 'startScreen_mobilelabel_28',
        'mobilecollapsibleset_18': 'startScreen_mobilecollapsibleset_18',
        'mobilecollapsblock_19': 'startScreen_mobilecollapsblock_19',
        'mobilecollapsblockheader_20': 'startScreen_mobilecollapsblockheader_20',
        'mobilegrid_38': 'startScreen_mobilegrid_38',
        'mobilegridcell_39': 'startScreen_mobilegridcell_39',
        'mobilelabel_35': 'startScreen_mobilelabel_35',
        'mobilegridcell_41': 'startScreen_mobilegridcell_41',
        'mobilelabel_61': 'startScreen_mobilelabel_61',
        'mobilecollapsblockcontent_21': 'startScreen_mobilecollapsblockcontent_21',
        'mobilegrid_76': 'startScreen_mobilegrid_76',
        'mobilegridcell_77': 'startScreen_mobilegridcell_77',
        'mobilelabel_81': 'startScreen_mobilelabel_81',
        'mobilelabel_82': 'startScreen_mobilelabel_82',
        'mobilelabel_83': 'startScreen_mobilelabel_83',
        'mobilegridcell_79': 'startScreen_mobilegridcell_79',
        'mobilelabel_84': 'startScreen_mobilelabel_84',
        'mobilecollapsblock_85': 'startScreen_mobilecollapsblock_85',
        'mobilecollapsblockheader_86': 'startScreen_mobilecollapsblockheader_86',
        'mobilegrid_88': 'startScreen_mobilegrid_88',
        'mobilegridcell_89': 'startScreen_mobilegridcell_89',
        'mobilelabel_95': 'startScreen_mobilelabel_95',
        'mobilegridcell_91': 'startScreen_mobilegridcell_91',
        'mobilelabel_96': 'startScreen_mobilelabel_96',
        'mobilecollapsblockcontent_87': 'startScreen_mobilecollapsblockcontent_87',
        'mobilegrid_98': 'startScreen_mobilegrid_98',
        'mobilegridcell_99': 'startScreen_mobilegridcell_99',
        'mobilelabel_97': 'startScreen_mobilelabel_97',
        'mobilelabel_103': 'startScreen_mobilelabel_103',
        'mobilegridcell_101': 'startScreen_mobilegridcell_101',
        'mobilelabel_104': 'startScreen_mobilelabel_104',
        'mobilebutton_29': 'startScreen_mobilebutton_29',
        'mobilenavbar_2': 'startScreen_mobilenavbar_2',
        'mobilenavbaritem_3': 'startScreen_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'startScreen_mobilenavbaritem_4',
        'mobilenavbaritem_105': 'startScreen_mobilenavbaritem_105'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */ 

    // Before Show
    var startScreen_beforeshow = function() {
            Apperyio.CurrentScreen = "startScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            if (localStorage.getItem("clovertoken") == "" || localStorage.getItem("clovertoken") == null)
	            redirect();
            getAccessToken();
            
            // TODO fire device events only if necessary (with JS logic)
            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events
    var startScreen_windowEvents = function() {

            $('#startScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var startScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_elementsExtraJS = function() {
            // screen (startScreen) extra code

            /* mobilecollapsblock_19 */

            $("#startScreen_mobilecollapsblock_19 .ui-collapsible-heading-toggle").attr("tabindex", "2");

            /* mobilecollapsblock_85 */

            $("#startScreen_mobilecollapsblock_85 .ui-collapsible-heading-toggle").attr("tabindex", "2");

        };

    // screen elements handler
    var startScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_mobilefooter1 [name="mobilenavbaritem_4"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('profileScreen', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobilefooter1 [name="mobilenavbaritem_4"]');
            $(document).off("click", '#startScreen_mobilefooter1 [name="mobilenavbaritem_105"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('chatScreen', {
                            transition: 'slide',
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobilefooter1 [name="mobilenavbaritem_105"]');

        };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});