//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cred
    {
        public Cred()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public string Merchantid { get; set; }
        public string EstbName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string EstbOwner { get; set; }
        public string SinchUsername { get; set; }
        public string SinchPassword { get; set; }
    
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
